name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake
        make
        tar -cf NDS_Banner_Editor.tar NDS_Banner_Editor
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: NDS_Banner_Editor.tar
        name: linux
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake
        make
        macdeployqt NDS_Banner_Editor.app/ -dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: NDS_Banner_Editor.dmg
        name: macos
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor.dmg
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        arch: win64_mingw81
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
    - name: make
      shell: cmd
      run: |
        qmake
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: release/NDS_Banner_Editor.exe
        name: windows
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: release/NDS_Banner_Editor.exe
        repo-token: ${{ secrets.GITHUB_TOKEN }}

