name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake
        make
        echo ===========================
        ls
    - name: Upload NDS_Banner_Editor
      uses: AButler/upload-release-assets@v2.0
      with:
        files: NDS_Banner_Editor
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake
        make
        /usr/local/opt/qt/bin/macdeployqt NDS_Banner_Editor.app/ -dmg
    - name: Upload NDS_Banner_Editor.dmg
      uses: AButler/upload-release-assets@v2.0
      with:
        files: NDS_Banner_Editor.dmg
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake
        make
    - name: Upload NDS_Banner_Editor.exe
      uses: AButler/upload-release-assets@v2.0
      with:
        files: NDS_Banner_Editor.exe
        repo-token: ${{ secrets.GITHUB_TOKEN }}

