name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        arch: win64_mingw81
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
    - name: make
      shell: cmd
      run: |
        qmake
        nmake
        cd release
        mt.exe -manifest Hello.exe.manifest -outputresource:Hello.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: release/NDS_Banner_Editor.exe
        name: windows
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: release/NDS_Banner_Editor.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}

