name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake -config release
        make -j$(nproc)
        make INSTALL_ROOT=appdir -j$(nproc) install
        cp NDS_Banner_Editor.desktop appdir/usr/share/applications
        cp icon.png appdir/usr/share/icons/hicolor/32x32/NDS_Banner_Editor.png

        curl -o linuxdeployqt -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod a+x linuxdeployqt

        ./linuxdeployqt appdir/usr/share/applications/NDS_Banner_Editor.desktop -appimage
        mv NDS_Banner_Editor-*-x86_64.AppImage NDS_Banner_Editor.AppImage
        tar -cf NDS_Banner_Editor_Linux_x64.tar NDS_Banner_Editor.AppImage
        tar -czf NDS_Banner_Editor_Linux_x64.tar.gz NDS_Banner_Editor.AppImage
    - name: ls
      run: ls -Rl appdir
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: NDS_Banner_Editor_Linux_x64.tar
        name: linux
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor_Linux_x64.tar.gz
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        qmake -config release
        make -j(sysctl -n hw.ncpu)
        macdeployqt NDS_Banner_Editor.app -dmg
        mv NDS_Banner_Editor.dmg NDS_Banner_Editor_mac_x64.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: NDS_Banner_Editor_Mac_x64.dmg
        name: macos
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor_Mac_x64.dmg
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
    - name: Install Qt
      run: pacman -S --noconfirm mingw-w64-x86_64-{gcc,make,qt5-static}
    - name: make
      run: |
        /mingw64/qt5-static/bin/qmake.exe -config release -config static
        mingw32-make.exe
        cd release
        tar.exe -czf NDS_Banner_Editor_Win_x64.zip NDS_Banner_Editor.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: release/NDS_Banner_Editor.exe
        name: windows
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: release/NDS_Banner_Editor_Win_x64.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}

